name: github-hosted runners

on:
  workflow_dispatch:

jobs:
  info:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: print os name
        run: echo "runners OS :" ${{ matrix.os }} 

      - name: Runners Hostname
        run: hostname

      - name: The current github user running the job
        run: echo "Current user :" ${{ github.actor }}
      
      - name: The current runner user running the job
        run: whoami


