name: schedule request

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - name: print date
        run: date

      - name: CPU usage      
        run: ps -aux | grep -i "cpu"