name: Secrets-pull

on:
  Workflow_dispatch:

jobs:
  secret1:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v4
          with:
            username: docker_user
            password: docker_token
        env:
          docker_user: ${{ vars.DOCKERHUB_USERNAME }}
          docker_token: ${{ secrets.DOCKERHUB_TOKEN }}  
        